---
title: "MA4605: Two Independent Groups Report"
author: "Name & ID Number"
date: "Date of lab session"
output: 
  html_document: 
    highlight: pygments
    theme: spacelab
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
library(tidyverse)

```

* * * 

First read in the data:

```{r}
steak = read.csv(file="Bacteria.csv")
```

## Exploratory analysis

### Exploratory plots

```{r, eval=TRUE, fig.height=4, fig.width=5}
# Create a boxplot. The fig.height and fig.width values above change the size of the plot produced in the output. 
ggplot(steak, aes(x=Packaging, y=Bacteria)) + geom_boxplot()
```

Create a QQ-plot for the CO2 group:

```{r, eval=TRUE, fig.height=4, fig.width=5}
CO2 = steak %>%
  filter(Packaging == "CO2")
ggplot(CO2, aes(sample=Bacteria)) + geom_qq() + geom_qq_line()
```

#### Exercise 1:

```{r, fig.height=4, fig.width=5}
# Put your code for Exercise 1 here

```
[Write your response for Exercise 1 here.]  


### Summary statistics
Next calculate some summary statistics. 

```{r}
steak %>%
  group_by(Packaging) %>%
  summarise(min = min(Bacteria), max = max(Bacteria),
            mean = mean(Bacteria), med = median(Bacteria),
            sd = sd(Bacteria), 
            q1 = quantile(Bacteria, probs = 0.25),
            q3 = quantile(Bacteria, probs = 0.75))
```


## Formal analysis

### Test for equal variances.
```{r}
var.test(data=steak, Bacteria ~ Packaging)
```  

### Test for equality of means.

```{r}
t.test(Bacteria ~ Packaging, data=steak, alternative='two.sided',
          var.equal=TRUE, paired=FALSE, mu=0, conf.level=0.95)
``` 


#### Exercise 2:

[Write your response for Exercise 2 here.]

